### ISSUE TITLE
MPV detection doesn't work when files contain ordered chapters

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#22]
I can't seem to get MAL to detect that I am playing anything from MPV. I've tried playing videos through both the .app and from the command application and I get no detection in either case. I am on Mac OS X 10.8.5. Crunchyroll Chrome detection I have confirmed works.

Edit: It does appear to work for some titles. 

Works:
`[Merchant] Regalia - 01 [720p].mkv`
`[HorribleSubs] Tales of Zestiria the X - 02 [1080p].mkv`

Doesn't work:
`[Coalgirls]_Aikatsu_014_(1280x720_Blu-ray_FLAC)_[4A1F723D].mkv`

Possibly your regex is incorrect.

**Comment by mlindner** [comment]
I've potentially found the problem. If I rename some other video to `[Coalgirls]_Aikatsu_014_(1280x720_Blu-ray_FLAC)_[4A1F723D].mkv` then malupdaterosx properly detects it. However it will not detect the original file. I believe this is because your current code rejects any lsof run that displays any file that contains a file with "OP" or "ED" in the filenames. When you run `lsof -c 'mpv' -Fn` it shows up with:
`n/Users/mlindner/Downloads/Aikatsu!/[Coalgirls]_Aikatsu_014_(1280x720_Blu-ray_FLAC)_[4A1F723D].mkv`
`n/Users/mlindner/Downloads/Aikatsu!/[Coalgirls]_Aikatsu_ED1_(1280x720_Blu-ray_FLAC)_[5B146AE2].mkv`
`n/Users/mlindner/Downloads/Aikatsu!/[Coalgirls]_Aikatsu_OP1_(1280x720_Blu-ray_FLAC)_[458C1DB4].mkv`

It happens to see that there is a file with ED or OP here and it immediately drops the parsing and figures that the file should not be parsed. This is based on my reading of your code here: https://github.com/Atelier-Shiori/malupdaterosx-cocoa/blob/a51b7a4db334b89dc2d0b75c5aefacba1b16c9fc/Detection.m#L106

**Comment by chikorita157** [comment]
The program checks the last most file in lsof, meaning that it will always get the OP1, which is an invalid episode and will ignore it. I will figure out a better way, possibly putting the file names in an array and filtering them before doing the recognition.

**Comment by chikorita157** [comment]
Fixed with https://github.com/Atelier-Shiori/malupdaterosx-cocoa/commit/593b6e0cb792079e8f9ceb22ab3044bdd4d9304d. This change will dump all the matched file names into an array and check each one in the detection method.
