### ISSUE TITLE
Future Features

### ISSUE THREAD

**Issue by chikorita157** [Atelier-Shiori/malupdaterosx-cocoa#3]
Reserved for future versions in consideration
- [x] O
- [x] Funimation Support

**Comment by Enuqt** [comment]
Is this still in Work or would u like some help?

**Comment by chikorita157** [comment]
I will eventually implement these features, but there are other features that need to be implemented such as rewatch support.

**Comment by Enuqt** [comment]
awesome u are still active will try and help the best i can Love ur work !

**Comment by mlindner** [comment]
Feature request idea, support importing different other websites formats into MAL. MAL already supports importing anidb, but I'd love to import the watch status from http://animecalendar.net/ and possibly other websites.

**Comment by chikorita157** [comment]
Importing of other lists will be implemented in MAL Library, not in MAL Updater OS X.
