### ISSUE TITLE
Freeze when resolving login items for unavailable AFP shares

### ISSUE THREAD

**Issue by swoolcock** [Atelier-Shiori/malupdaterosx-cocoa#33]
I have a keychain item setup to automatically connect to my NAS on boot.  My NAS was turned off, so the app got stuck trying to resolve it.

Freezes on the `LSSharedFileListItemResolve` call in `[LoginItems itemRefInLoginItems]`.  Example log for my NAS (Jade) is:

`2017-04-17 15:22:06.831228 MAL Updater OS X[1601:16455] afp_GetURLFromURLRemountInfo: address string is jade`
`2017-04-17 15:22:06.831242 MAL Updater OS X[1601:16455] NewAFPURL: returning realurl = :afp://;AUTH=No%20User%20Authent@jade/Music:`

**Comment by chikorita157** [comment]
I changed the login item implementation to something else. Can you try this build and see if it has the same issues?
[malupdaterosx-2.3.3-test.zip](https://github.com/Atelier-Shiori/malupdaterosx-cocoa/files/926099/malupdaterosx-2.3.3-test.zip)

**Comment by swoolcock** [comment]
Nope, still seems to freeze.  To test it, I'm unplugging my NAS and waiting for the connection to time out, then open the Preferences panel in MAL Updater.  The fox icon stays depressed in the status bar, and the process has to be killed.

**Comment by chikorita157** [comment]
I found out that LSSharedFileListItemResolve is deprecated. I replaced it with LSSharedFileListItemCopyResolvedURL. Try now.
[malupdaterosx-test2.zip](https://github.com/Atelier-Shiori/malupdaterosx-cocoa/files/930158/malupdaterosx-test2.zip)

**Comment by chikorita157** [comment]
I forgot to add kLSSharedFileListNoUserInteraction|kLSSharedFileListDoNotMountVolumes, this should now work.
[malupdaterosx-test3.zip](https://github.com/Atelier-Shiori/malupdaterosx-cocoa/files/930583/malupdaterosx-test3.zip)

**Comment by swoolcock** [comment]
Yep, that fixed it.  Nice work.  ;)
