### ISSUE TITLE
Updater parses streamlink URLs that contain "&" characters as "&amp;"

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#34]
When automatically getting streamlink URLs from a playing streamlink process, if the anime title has an '&' character it is parsed instead as "&amp;". This usually causes the series discovery logic to fail and manually picking the correct anime title is needed.

Example URL to try: http://www.crunchyroll.com/alice-zoroku/episode-3-cards-733429

**Comment by chikorita157** [comment]
Fixed with https://github.com/Atelier-Shiori/Streamlinkdetect/commit/faa7332bc3d57d0683c02fa657e769b683f7232a
