### ISSUE TITLE
MAL Updater tries to scrobble on a non-video page on Crunchyroll

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#36]
When viewing this page http://www.crunchyroll.com/videos/anime/seasons/spring-2017 the program tries to scrobble this as a title and fails and asks for suggestions for an anime titled "Crunchyroll".

**Comment by chikorita157** [comment]
It seems to be one of the regular expressions rules which can detect urls like 

http://www.crunchyroll.com/trinity-seven/trinity-seven-eternity-library-alchemic-girl-trinity-seven-eternity-library-alchemic-girl-732735?t=0

Of course it will bring back false positives. If you can come up with a better rule that reduce the false positives, it will be great.

https://github.com/Atelier-Shiori/detectstream/blob/master/detectstream/MediaStreamParse.m

Sent from my iPhone 6
(Shijou Takane - 四条貴音)

**Comment by chikorita157** [comment]
Fixed with https://github.com/Atelier-Shiori/detectstream/commit/21debd354f9ca1ce08c33c1b48e20eb61806c7cd

Added check to see if the title is "Crunchyroll". If so, it will ignore that tab.
