### ISSUE TITLE
Correction was not successful

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#37]
For this URL http://www.crunchyroll.com/attack-on-titan/episode-26-beast-titan-733245 it fails find the title and then when you attempt to correct the title it fails.

**Comment by chikorita157** [comment]
It's because the episode number exceeds the first season of Attack on Titan (which has total of 25 episodes) and there is no exception rule for that title. For this to be detected properly, I need the correct title for the 2nd cour to make an auto exception for this title.

**Comment by chikorita157** [comment]
I added the exception rules. The exception rule for that title only took account for the Japanese title, not the localized title. Just update the Auto Exceptions Rule in Preferences and it should detect properly.
