### ISSUE TITLE
It says that my username and/or password are incorrect

### ISSUE THREAD

**Issue by serpentineheart** [Atelier-Shiori/malupdaterosx-cocoa#40]
Hi, I have a problem with both MAL updater OS X. MAL updater OS X says that my username and/or password are incorrect, even when I have checked that they aren't incorrect.
Please help!

**Comment by chikorita157** [comment]
What version are you using? It seems to be working fine here. Note that MAL Updater OS X only support username login, not social network logins.

**Comment by serpentineheart** [comment]
I´m using MAL Updater OS X Version 2.3.4 (2.3.4) and a Mac OS X Yosemite version 10.10.5

**Comment by chikorita157** [comment]
It seems that while the authorized comes back as OK, MAL Updater OS X expects the HTTP status code 200 OK for a successful login. Sometimes, it seems to bring back a 0. It might be a bug with the API. If you keep trying to login and you know the credentials is OK, it will eventually take. I will investigate if this is actually an API bug or not or whether or not MAL Updater OS X should also check for the authorized:OK status.

**Comment by chikorita157** [comment]
I tested the verify credentials API with a rest client and I am able to login properly. May be an API bug or something.

**Comment by serpentineheart** [comment]
Alright, thank you for your help :)
