### ISSUE TITLE
2.3.7 does not launch on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#43]
The application simply refuses to open after updating. Downgrading to 2.3.6 restores working behavior.

**Comment by chikorita157** [comment]
![2017-11-14_06-10-19](https://user-images.githubusercontent.com/161183/32777030-a6e0e7ae-c902-11e7-92c7-e101578e6343.png)

As seen in the screenshot, I managed to fix it. It seems that one of the frameworks build target was set to 10.12. This is now fixed and an update will be added shortly.

**Comment by chikorita157** [comment]
2.3.7.1 is released to fix this issue. I tested an update from 2.3.6 to 2.3.7.1 in a virtual machine and it's confirmed working.
