### ISSUE TITLE
Anime titled "The Ancient Magus' Bride" is not found and correction fails

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#46]
http://www.crunchyroll.com/the-ancient-magus-bride/episode-14-looks-breed-love-759729 when played with streamlink, mal updater osx fails to find the title and when correction is attempted the correction fails. If I had to guess, I think you are not properly escaping quote characters like ' or ".

**Comment by chikorita157** [comment]
It have to do with how alternate titles are checked while comparing the detected title with each entry from the search results to get the corresponding id for the title. The alternate title check wasn't working properly, but this have been fixed and an update will be released soon.
