### ISSUE TITLE
Client authentication failed

### ISSUE THREAD

**Issue by TopoR** [Atelier-Shiori/malupdaterosx-cocoa#52]
Hi!
It seems, that MAL Updater is broken since yesterday. Can't connect to the MAL, while Shukofukurou works perfectly well.
MAL Updater OS X Pro Version 2.5a3 (Build 20180507).
<img width="712" alt="screen shot 2018-05-12 at 21 15 17" src="https://user-images.githubusercontent.com/4129779/39960356-06451350-562a-11e8-9ee9-a6dab7e0cf34.png">

**Comment by moyitpro** [comment]
The MyAnimeList developer somehow resetted the API and invalidated the client IDs. For now, use the stable release until I can release another Alpha, which will work with the new API.

The stable release can be downloaded at: https://malupdaterosx.moe/download.php
